from audit.enums import LogLevel

LARGE_AMOUNT_COEFFICIENT = 30
FREQUENT_OPERATIONS_COEFFICIENT = 5
NEW_ACCOUNT_COEFFICIENT = 20
NIGHT_OPERATIONS_COEFFICIENT = 20

LOG_LEVEL_ORDER = [
    LogLevel.INFO,
    LogLevel.WARNING,
    LogLevel.ERROR,
]